<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-CAELC20" ignored="0" name="Test" tests="3" failures="1" timestamp="2022-05-13T19:00:29 IST" time="43.478" errors="0">
  <testcase name="loginFuncationality" time="1.479" classname="TestNGProgram.TestNG4"/>
  <testcase name="validateTitle" time="0.024" classname="TestNGProgram.TestNG4"/>
  <testcase name="validateUrl" time="0.01" classname="TestNGProgram.TestNG4">
    <failure type="java.lang.AssertionError" message="expected [https://opensource-demo.orangehrmlive.com/index.php/dashboard] but found [https://opensource-demo.orangehrmlive.com/index.php/auth/validateCredentials]">
      <![CDATA[java.lang.AssertionError: expected [https://opensource-demo.orangehrmlive.com/index.php/dashboard] but found [https://opensource-demo.orangehrmlive.com/index.php/auth/validateCredentials]
at TestNGProgram.TestNG4.validateUrl(TestNG4.java:38)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- validateUrl -->
</testsuite> <!-- Test -->
